# Generated by Django 5.1.7 on 2025-03-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(help_text='ISBN Number', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('pages', models.IntegerField()),
                ('publication_date', models.DateField()),
            ],
        ),
    ]
